version: 2.0
jobs:
  build:
    docker:
      - image: bitnami/node:8
    parallelism: 4
    steps:
      - run: install_packages procps git openssh-client htop
      - add_ssh_keys
      - checkout
      - run: "npm install -g yarn@1.5.1"
      - run: "yarn install"
      - run:
          name: Test
          command: "CIRCLE_NODE_INDEX=1 yarn test"
  push:
    docker:
      - image: artsy/hokusai:0.4.0
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - run:
          name: Push
          command: hokusai registry push --tag $CIRCLE_SHA1 --force --overwrite
  deploy:
    docker:
      - image: artsy/hokusai:0.4.0
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Deploy
          command: hokusai staging deploy $CIRCLE_SHA1

workflows:
  version: 2
  default:
    jobs:
      - build
      - push:
          filters:
            branches:
              only: master
          requires:
            - build
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - push
