version: 2.0
jobs:
  test:
    docker:
      - image: artsy/hokusai:0.4.0
    parallelism: 4
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - run:
          name: Test
          command: hokusai test
workflows:
  version: 2
  default:
    jobs:
      - test
