version: 2.0
jobs:
  acceptance:
    docker:
      - image: circleci/node:8-stretch-browsers
    parallelism: 1
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Acceptance Tests
          command: "yarn install && yarn acceptance src/test/acceptance/*.js"
  test:
    docker:
      - image: artsy/hokusai:0.4.0
    parallelism: 4
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - run:
          name: Test
          command: "hokusai test"
  build:
    docker:
      - image: artsy/hokusai:0.4.0
    steps:
      - run:
          name: "OK"
          command: "echo All Tests Pass!"
  push:
    docker:
      - image: artsy/hokusai:0.4.0
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - run:
          name: Push
          command: hokusai registry push --tag $CIRCLE_SHA1 --force --overwrite
  deploy:
    docker:
      - image: artsy/hokusai:0.4.0
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Deploy
          command: hokusai staging deploy $CIRCLE_SHA1

workflows:
  version: 2
  default:
    jobs:
      - test
      - acceptance
      - build:
          requires:
            - test
            - acceptance
      - push:
          requires:
            - build
      - deploy:
          requires:
            - push

